name: Market Data Robot

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-robot:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dosyayı yazmak için tam yetki veriyoruz
    steps:
      - name: Kodları indir
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Gerekli kütüphaneyi yükle
        run: pip install requests

      - name: Robotu Çalıştır
        run: python agent.py

      - name: Otomatik Kaydet ve Gönder
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Robot: Nijerya verileri güncellendi"
          file_pattern: 'data.json' # Sadece bu dosyayı günceller
